package com.netbiis;
// Generated 3 de nov. de 2022 15:36:31 by Hibernate Tools 4.3.6.Final

import java.sql.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Pagamento generated by hbm2java
 */
@Entity
@Table(name = "pagamento")
public class Pagamento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private PagamentoId id;
	private Cliente cliente;
	private Cursos cursos;
    private String dataInscricao;
    
	public Pagamento() {
	}


	
	public Pagamento(PagamentoId id, Cliente cliente, Cursos cursos) {
		this.id = id;
		this.cliente = cliente;
		this.cursos = cursos;
	}
	
	public Pagamento(PagamentoId id, String dataInscricao) {
		this.id = id;
		this.dataInscricao = dataInscricao;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "dataInscricao", column = @Column(name = "dataInscricao", nullable = false, length = 10)),
			@AttributeOverride(name = "pagidCliente", column = @Column(name = "pagidCliente", nullable = false)),
			@AttributeOverride(name = "pagCdcurso", column = @Column(name = "pagCdcurso", nullable = false)) })
	public PagamentoId getId() {
		return this.id;
	}

	public void setId(PagamentoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pagidCliente", nullable = false, insertable = false, updatable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pagCdcurso", nullable = false, insertable = false, updatable = false)
	public Cursos getCursos() {
		return this.cursos;
	}

	public void setCursos(Cursos cursos) {
		this.cursos = cursos;
	}
	
	@Override
	public String toString() {
		return "Pagamento => [Identificação: "+id+" , Cliente: "+id.getPagidCliente()+" , Curso: "+id.getPagCdcurso()+" ] ";
	}

	
	@JoinColumn(name = "dataInscricao", nullable = false, insertable = false, updatable = false)
	public String getDataInscricao() {
		return dataInscricao;
	}

	public void setDataInscricao(String dataInscricao) {
		this.dataInscricao = dataInscricao;
	}

	
}
